# Generated by Django 2.1 on 2018-08-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('imgfile', models.CharField(default='', max_length=250)),
                ('imgcap', models.CharField(default='', max_length=250)),
                ('category', models.CharField(max_length=250, verbose_name='category')),
                ('formula', models.CharField(max_length=250, verbose_name='formula')),
                ('strunz_classification', models.CharField(max_length=500, verbose_name='strunz classification')),
                ('color', models.CharField(max_length=250, verbose_name='color')),
                ('crystal_system', models.CharField(max_length=250, verbose_name='crystal system')),
                ('unit_cell', models.CharField(max_length=250, verbose_name='unit cell')),
                ('crystal_symmetry', models.CharField(max_length=250, verbose_name='crystal symmetry')),
                ('cleavage', models.CharField(max_length=250, verbose_name='cleavage')),
                ('mohs_scale_hardness', models.CharField(max_length=250, verbose_name='mohs scale hardness')),
                ('luster', models.CharField(max_length=250, verbose_name='luster')),
                ('streak', models.CharField(max_length=250, verbose_name='streak')),
                ('diaphaneity', models.CharField(max_length=250, verbose_name='diaphaneity')),
                ('optical_properties', models.CharField(max_length=250, verbose_name='optical properties')),
                ('refractive_index', models.CharField(max_length=250, verbose_name='refractive index')),
                ('crystal_habit', models.CharField(max_length=250, verbose_name='crystal habit')),
                ('specific_gravity', models.CharField(max_length=250, verbose_name='specific gravity')),
                ('group', models.CharField(max_length=250, verbose_name='group')),
            ],
        ),
    ]
