# Generated by Django 2.1 on 2018-08-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('imgfile', models.CharField(default='', max_length=250)),
                ('imgcap', models.CharField(default='', max_length=250)),
                ('category', models.CharField(default='', max_length=250)),
                ('formula', models.CharField(default='', max_length=250)),
                ('strunz_class', models.CharField(default='', max_length=250)),
                ('color', models.CharField(default='', max_length=250)),
                ('crystal_sys', models.CharField(default='', max_length=250)),
                ('unit_cell', models.CharField(default='', max_length=250)),
                ('crystal_symmetry', models.CharField(default='', max_length=250)),
                ('cleavage', models.CharField(default='', max_length=250)),
                ('ms_hardness', models.CharField(default='', max_length=250)),
                ('luster', models.CharField(default='', max_length=250)),
                ('streak', models.CharField(default='', max_length=250)),
                ('diaphaneity', models.CharField(default='', max_length=250)),
                ('optical_prop', models.CharField(default='', max_length=250)),
                ('refractive_index', models.CharField(default='', max_length=250)),
                ('crystal_habit', models.CharField(default='', max_length=250)),
                ('specific_gravity', models.CharField(default='', max_length=250)),
                ('group', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
