# Generated by Django 2.1 on 2018-08-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_load_rocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineral',
            old_name='crystal_sys',
            new_name='crystal_system',
        ),
        migrations.RenameField(
            model_name='mineral',
            old_name='ms_hardness',
            new_name='mohs_scale_hardness',
        ),
        migrations.RenameField(
            model_name='mineral',
            old_name='optical_prop',
            new_name='optical_properties',
        ),
        migrations.RenameField(
            model_name='mineral',
            old_name='strunz_class',
            new_name='strunz_classification',
        ),
    ]
