# Generated by Django 2.1 on 2018-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0003_auto_20180827_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='category',
            field=models.CharField(max_length=250, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='cleavage',
            field=models.CharField(max_length=250, verbose_name='cleavage'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='color',
            field=models.CharField(max_length=250, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystal_habit',
            field=models.CharField(max_length=250, verbose_name='crystal habit'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystal_symmetry',
            field=models.CharField(max_length=250, verbose_name='crystal symmetry'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystal_system',
            field=models.CharField(max_length=250, verbose_name='crystal system'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='diaphaneity',
            field=models.CharField(max_length=250, verbose_name='diaphaneity'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='formula',
            field=models.CharField(max_length=250, verbose_name='formula'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='group',
            field=models.CharField(max_length=250, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='luster',
            field=models.CharField(max_length=250, verbose_name='luster'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='mohs_scale_hardness',
            field=models.CharField(max_length=250, verbose_name='mohs scale hardness'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='optical_properties',
            field=models.CharField(max_length=250, verbose_name='optical properties'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='refractive_index',
            field=models.CharField(max_length=250, verbose_name='refractive index'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='specific_gravity',
            field=models.CharField(max_length=250, verbose_name='specific gravity'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='streak',
            field=models.CharField(max_length=250, verbose_name='streak'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='strunz_classification',
            field=models.CharField(max_length=250, verbose_name='strunz classification'),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='unit_cell',
            field=models.CharField(max_length=250, verbose_name='unit cell'),
        ),
    ]
